### ISSUE TITLE
Support --watch flag

### ISSUE THREAD

**Issue by chrisweight-elsewhen** [Roozenboom/rbnx#5]
### Is your feature request related to a problem?

As a developer, I would like to be able to run my e2e tests with `--watch`, so that I am able to more-rapidly develop my e2e testing Journeys.

### Describe the solution or feature you'd like

Accept a `watch` parameter defined in the executor schema that is passed to the executor and `runWdio` method, enabling the developer to run wdio in watch mode.

### Describe alternatives you've considered

There aren't really any alternative approaches I can see to this that aren't hacky when consuming this package to setup WDIO e2e tests

**Comment by Roozenboom** [comment]
Thanks for reporting! I agree, this is a missing feature and would be a nice enhancement. 
I'll look into this and will update this issue.

**Comment by chrisweight-elsewhen** [comment]
Many thanks!
